"""Smith gloss -> Lexibank concept ID (concepts.csv ID column).

Only explicit mappings are used for concept lookup (no fuzzy matching).
"""

from __future__ import annotations

# None = no Lexibank concept; pair excluded from permutation test.
GLOSS_TO_LEXIBANK_CONCEPT: dict[str, str | None] = {
    "1sg": "i",
    "2sg": "you",
    "afraid; fear": "fearbeafraid",
    "ant": "ant",
    "arm": "arm",
    "bathe": "bathe",
    "bear": "bear",
    "big": "big",
    "bird; chicken": "bird",
    "bitter": "bitter",
    "blow": "blowofwind",
    "boat": "boat",
    "body hair": "hair",
    "borrow": "borrow",
    "buy/sell": "buy",
    "carry on a pole": "carry",
    "centipede": "centipede",
    "chaff; bran": "chaffhusk",
    "chest": "chest",
    "child1": "childyounghuman",
    "cold": "cold",
    "cook": "cooksomething",
    "cry": "cry",
    "dark; black": "black",
    "deaf": "deaf",
    "deep": "deep",
    "die": "die",
    "dream": "dream",
    "drop; fall": "fall",
    "duck": "duck",
    "eat": "eat",
    "eight": "eight",
    "excrement": "faecesexcrement",
    "eye": "eye",
    "fart": "fart",
    "fingernail": "fingernail",
    "fire": "fire",
    "five": "five",
    "fish poison": "poison",
    "flow": "flow",
    "foot1": "foot",
    "foot2": "foot",
    "forget": "forget",
    "fruit": "fruit",
    "full": "full",
    "hand": "hand",
    "handspan": "handspan",
    "head": "head",
    "hold; grab": "hold",
    "hole": "hole",
    "hook": "fishhook",
    "hot; warm": "warm",
    "hungry": "behungry",
    "knife": "knife",
    "leaf": "leaf",
    "leech": "leech",
    "leg": "leg",
    "lick": "lick",
    "liver": "liver",
    "loom; weave": "weave",
    "louse": "louse",
    "maggot": "larva",
    "moon": "moon",
    "mushroom": "mushroom",
    "navel": "navel",
    "nest": "nest",
    "new": "new",
    "nine": "nine",
    "nose": "nose",
    "one": "one",
    "otter": "otter",
    "outside; (go outside)": "outside",
    "pangolin": "pangolin",
    "pick up; lift; take": "take",
    "pig": "pig",
    "plant": "plantvegetation",
    "rain": "rainprecipitation",
    "rattan": "rattan",
    "raw; (a)live": "raw",
    "road": "road",
    "scale; skin": "skin",
    "seed": "seed",
    "seven": "seven",
    "shadow": "shadow",
    "sharp": "sharp",
    "shoulder": "shoulder",
    "shrimp": "shrimp",
    "sick": "sick",
    "six": "six",
    "skin": "skin",
    "skinny": "thin",
    "sky": "sky",
    "snot": "nasalmucussnot",
    "sour": "sour",
    "stand": "stand",
    "star": "star",
    "steal": "steal",
    "stomach": "stomach",
    "stone": "stone",
    "sweet": "sweet",
    "tail": "tail",
    "taro": "taro",
    "this": "this",
    "three": "three",
    "tie; bundle": "tie",
    "to fly": "flymovethroughair",
    "to taste": "taste",
    "tongue2": "tongue",
    "tooth": "tooth",
    "transplant; plant": "plantsomething",
    "turtle": "turtle",
    "two": "two",
    "village": "village",
    "vomit": "vomit",
    "wash": "wash",
    "water": "water",
    "wing": "wing",
    "winnowing basket": "winnowing",
    "younger siblings": "youngerbrother",
}
